# Generated by Django 5.1.7 on 2025-03-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='puntaje_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='perfil',
            field=models.CharField(max_length=100),
        ),
    ]
