# Generated by Django 5.1.7 on 2025-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_resultado_puntaje_minimo_alter_opcion_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntaje_minimo',
            field=models.IntegerField(),
        ),
    ]
