# Generated by Django 5.1.7 on 2025-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_opcion_texto_alter_pregunta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puntaje_obtenido',
            field=models.IntegerField(default=0),
        ),
    ]
